package co.model.pojos;
// Generated 22/11/2018 01:03:38 PM by Hibernate Tools 4.3.1

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;




/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer idComentario;
     private String tituloComentario;
     private String contenidoComentario;
     private String nombreUsuario;

    

    public Comentario(String tituloComentario, String contenidoComentario, String nombreUsuario) {
       this.tituloComentario = tituloComentario;
       this.contenidoComentario = contenidoComentario;
       this.nombreUsuario = nombreUsuario;
    }

    public Comentario(Integer idComentario) {
        this.idComentario=idComentario;
    }

    public Comentario(Integer idComentario, String tituloComentario, String contenidoComentario, String nombreUsuario) {
        this.idComentario= idComentario;
        this.tituloComentario= tituloComentario;
        this.contenidoComentario= contenidoComentario;
        this.nombreUsuario = nombreUsuario;
    }
   
    public Integer getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(Integer idComentario) {
        this.idComentario = idComentario;
    }
    public String getTituloComentario() {
        return this.tituloComentario;
    }
    
    public void setTituloComentario(String tituloComentario) {
        this.tituloComentario = tituloComentario;
    }
    public String getContenidoComentario() {
        return this.contenidoComentario;
    }
    
    public void setContenidoComentario(String contenidoComentario) {
        this.contenidoComentario = contenidoComentario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    


}


