package co.model.pojos;
// Generated 22/11/2018 01:03:38 PM by Hibernate Tools 4.3.1



/**
 * Noticia generated by hbm2java
 */
public class Noticia  implements java.io.Serializable {


     private Integer idNoticia;
     private String tituloNoticia;
     private String contenido;
     private String url;
     private String nombreUsuario;
     private String fechaNoticia;

    public Noticia() {
    }

    public Noticia(String tituloNoticia, String contenido, String url, String nombreUsuario, String fechaNoticia) {
       this.tituloNoticia = tituloNoticia;
       this.contenido = contenido;
       this.url = url;
       this.nombreUsuario = nombreUsuario;
       this.fechaNoticia = fechaNoticia;
    }

    public Noticia(Integer idNoticia) {
        this.idNoticia = idNoticia;
    }

    public Noticia(Integer idNoticia, String tituloNoticia, String contenido, String url, String nombreUsuario) {
        this.idNoticia = idNoticia;
        this.tituloNoticia= tituloNoticia;
        this.contenido= contenido;
       this.url = url;
       this.nombreUsuario = nombreUsuario;
  
    }
   
    public Integer getIdNoticia() {
        return this.idNoticia;
    }
    
    public void setIdNoticia(Integer idNoticia) {
        this.idNoticia = idNoticia;
    }
    public String getTituloNoticia() {
        return this.tituloNoticia;
    }
    
    public void setTituloNoticia(String tituloNoticia) {
        this.tituloNoticia = tituloNoticia;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getFechaNoticia() {
        return this.fechaNoticia;
    }
    
    public void setFechaNoticia(String fechaNoticia) {
        this.fechaNoticia = fechaNoticia;
    }




}


