package co.model.pojos;
// Generated 22/11/2018 01:03:38 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsurario;
     private String nombre;
     private String apellido;
     private String email;
     private String nombreUsuario;
     private String clave;

    public Usuario() {
    }

    public Usuario(String nombre, String apellido, String email, String nombreUsuario, String clave) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
    }

    public Usuario(String nombreUsuario, String clave) {
        this.nombreUsuario = nombreUsuario;
        this.clave = clave;
    }

    public Usuario(Integer idUsuario) {
        this.idUsurario =idUsuario;
    }

    public Usuario(Integer idUsuario, String nombre, String apellido, String email, String nombreUsuario, String clave) {
        this.idUsurario =idUsuario;
        this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.nombreUsuario = nombreUsuario;
       this.clave = clave;
    }
   
    public Integer getIdUsurario() {
        return this.idUsurario;
    }
    
    public void setIdUsurario(Integer idUsurario) {
        this.idUsurario = idUsurario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }




}


